# Run the line before the first run
# git clone --progress --verbose https://github.com/TBMPQF/TBM_CPU_V2.git /data
services:
  bot:
    restart: unless-stopped
    image: node:lts-alpine
    container_name: tbm-cpu
    hostname: tbm-cpu
    labels:
      diun.enable: true
      diun.watch_repos: true
    environment:
      PUID: 1000
      PGID: 100    
      TZ: Europe/Paris
    volumes:
      - /${DOCKER_DATA_DIRECTORY}/repos/home-docker/timezone:/etc/timezone:ro
      - tbm-cpu:/data
    command:
      - sh
      - -c
      - > 
        cd /data &&
        apk add --no-cache ffmpeg git py3-pip &&        
        touch /data/logs/current_output.log /data/logs/current_error.log &&
        mv /data/logs/current_output.log /data/logs/output.log &&
        mv /data/logs/current_error.log /data/logs/error.log &&
        git reset --hard && git pull origin main && git checkout ${COMMIT_REF} &&
        chmod +x /data/CreateConfig.sh && /data/CreateConfig.sh &&
        node /data/index.js > >(awk '{ print strftime("%d/%m_%Hh%Mm%Ss"), $0; fflush(); }' | tee -a /data/logs/current_output.log) 2> >(awk '{ print strftime("%d/%m_%Hh%Mm%Ss"), $0; fflush(); }' | tee -a /data/logs/current_error.log >&2)
    networks:
    - tbm-cpu

volumes:
  tbm-cpu:
    name: tbm_cpu
networks:
  tbm-cpu:
    name: tbm-cpu