services:
  bot:
    restart: no
    image: node:22.6.0-alpine
    container_name: tbm-cpu
    hostname: tbm-cpu
    labels:
      diun.enable: true
      diun.watch_repos: true
    environment: 
      TZ: Europe/Paris
    volumes:
      - tbm-cpu:/data
    env_file:
      - .env
    command:
      - sh
      - -c
      - > 
        apk add --no-cache build-base cairo-dev ffmpeg gawk git giflib-dev jpeg-dev jq nano pango-dev pixman-dev py3-pip &&
        cd /data &&
        wget -qO- https://raw.githubusercontent.com/Nicolas-mahe/Bot-Discord/refs/heads/main/init-repos.sh | sh &&
        git reset --hard && git pull origin main && git checkout ${COMMIT_REF} &&
        npm install &&
        chmod +x /data/docker/entrypoint-docker.sh && /data/docker/entrypoint-docker.sh
    networks:
      - tbm_cpu

volumes:
  tbm-cpu:
    name: tbm_cpu

networks:
  tbm_cpu:
    name: tbm_cpu