services:
  bot:
    restart: unless-stopped
    image: node:lts-alpine
    container_name: tbm-cpu
    hostname: tbm-cpu
    labels:
      diun.enable: true
      diun.watch_repos: true
    environment:
      PUID: 1000
      PGID: 100    
      TZ: Europe/Paris
    volumes:
      - /${DOCKER_DATA_DIRECTORY}/repos/home-docker/timezone:/etc/timezone:ro
      - tbm-cpu:/data
    env_file:
      - stack.env
    command:
      - sh
      - -c
      - > 
        apk add --no-cache ffmpeg git py3-pip &&
        wget -qO- https://raw.githubusercontent.com/Nicolas-mahe/Bot-Discord/refs/heads/main/init-repos.sh | sh &&
        cd /data &&
        git reset --hard && git pull origin main && git checkout ${COMMIT_REF} &&
        chmod +x /data/CreateConfig.sh && /data/CreateConfig.sh &&
        node /data/index.js > >(awk '{ print strftime("%d/%m_%Hh%Mm%Ss"), $0; fflush(); }' | tee -a /data/logs/current_output.log) 2> >(awk '{ print strftime("%d/%m_%Hh%Mm%Ss"), $0; fflush(); }' | tee -a /data/logs/current_error.log >&2)
    networks:
    - tbm-cpu

volumes:
  tbm-cpu:
    name: tbm_cpu
networks:
  tbm-cpu:
    name: tbm-cpu