version: '3'

services:
  Bot:
    container_name: CPU_TBM
    image: node:lts-alpine
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.cpu.tls: true
      traefik.http.routers.cpu.entrypoints: websecure
      traefik.http.routers.cpu.rule: Host(`cpu.${PERSONAL_DOMAINE_NAME}`)
      traefik.http.services.cpu.loadbalancer.server.port: 80
    networks:
      - web
    volumes:
      - data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    command:
      - sh
      - -c
      - >
        find /data/ -mindepth 1 -delete &&
        apk update && apk add ffmpeg git &&
        git clone https://github.com/TBMPQF/TBM_CPU_V2.git /data &&
        wget https://raw.githubusercontent.com/Nicolas-mahe/Bot-Discord/main/CreateConfig.sh -O /data/CreateConfig.sh &&
        cd /data && chmod +x ./CreateConfig.sh && ./CreateConfig.sh && git checkout ${COMMIT_REF} &&
        node --trace-deprecation /data/index.js;
networks:
    web:
      external: true
volumes:
  data: {}