services:
  Bot:
    container_name: TBM_CPU
    image: node:19.8.1
    restart: unless-stopped
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.minecraft_test.rule=Host(`tbmpqf.laura-et-nicolas.com`)"
     - "traefik.http.routers.minecraft_test.entrypoints=web"
    environment:
      - TZ= Europe/Paris
    networks:
      - web
    volumes:
      - data:/data
      - git:/git:ro
    command: 
        - bash
        - -c
        - >
          rm -r /data;
          git clone https://github.com/TBMPQF/TBM_CPU_V2.git /data;
          cp /git/config.json /data/config.json;
          cd /data;
          git checkout 79d43cd6d0e12c1595c27027956ffb79b059c3d8;
          mv /data/Commands /data/commands;
          nodejs index.js;
networks:
    web:
      external: true
volumes:
  data: {}  
  git: {}