# Run the line before the first run
# git clone https://github.com/TBMPQF/TBM_CPU_V2.git /data
version: '3'

services:
  bot:
    restart: unless-stopped
    image: node:lts-alpine
    container_name: tbm-cpu
    hostname: tbm-cpu
    environment:
      PUID: 1002
      PGID: 100    
      TZ: Europe/Paris
    volumes:
      - tbm-cpu:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    command:
      - sh
      - -c
      - > 
        cd /data &&
        apk update && apk add ffmpeg git &&
        git pull origin main && git checkout ${COMMIT_REF}&&
        chmod +x ./CreateConfig.sh && ./CreateConfig.sh &&
        node --trace-deprecation /data/index.js;
    networks:
    - tbm-cpu

volumes:
  tbm-cpu:
    name: tbm_cpu
networks:
  tbm-cpu:
    name: tbm-cpu