version: "3"

services:
  Bot:
    container_name: CPU_TBM
    image: node:lts-alpine
    restart: no
    labels:
      traefik.enable: true
      traefik.http.routers.cpu.tls: true
      traefik.http.routers.cpu.entrypoints: websecure
      traefik.http.routers.cpu.rule: Host(`cpu.${PERSONAL_DOMAINE_NAME}`)
      traefik.http.services.cpu.loadbalancer.server.port: 80
    environment:
      UID: ${PERSONAL_UID_CPU}
      GID: ${PERSONAL_GID_CPU}
    networks:
      - web
    volumes:
      - data:/data
      - git:/git
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command:
      - sh
      - -c
      - >
        rm -rf /data/* &&
        apk update && apk add ffmpeg && apk add git &&
        git clone https://github.com/TBMPQF/TBM_CPU_V2.git /data &&
        cd /data && git checkout ${COMMIT_REF} &&
        chmod +x /git/CreateConfig.sh &&
        /git/CreateConfig.sh &&
        cp /git/config.json /data/config.json &&
        node --trace-deprecation /data/index.js;
networks:
    web:
      external: true
volumes:
  data: {}  
  git: {}