version: '3'

services:
  Bot:
    container_name: tbm_cpu
    hostname: tbm_cpu
    image: node:lts-alpine
    restart: unless-stopped
    env_file:
      - stack.env
    volumes:
      - /home/docker/tbm-cpu:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command:
      - sh
      - -c
      - >
        find /data/ -mindepth 1 -delete &&
        apk update && apk add ffmpeg git &&
        git clone https://github.com/TBMPQF/TBM_CPU_V2.git /data &&
        cd /data && chmod +x ./CreateConfig.sh && ./CreateConfig.sh && git checkout ${COMMIT_REF} &&
        node --trace-deprecation /data/index.js;
    networks:
    - web

networks:
  web:
    external: true