# Run the line before the first run
# git clone --progress --verbose https://github.com/TBMPQF/TBM_CPU_V2.git /data
version: '3'

services:
  bot:
    restart: unless-stopped
    image: node:lts-alpine
    container_name: tbm-cpu
    hostname: tbm-cpu
    labels:
      diun.enable: true
      diun.watch_repos: true
    environment:
      PUID: 1002
      PGID: 100    
      TZ: Europe/Paris
    volumes:
      - ./tbm-cpu:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    command:
      - sh
      - -c
      - > 
        find /data/ -mindepth 1 -delete &&
        apk update && apk add ffmpeg git && git config --global --add safe.directory /data &&
        git clone --progress --verbose https://github.com/TBMPQF/TBM_CPU_V2.git /data &&
        cd /data && chmod +x ./CreateConfig.sh && ./CreateConfig.sh && git checkout ${COMMIT_REF} &&
        node --trace-deprecation /data/index.js;
    networks:
    - tbm-cpu

volumes:
  tbm-cpu:
    name: tbm_cpu
networks:
  tbm-cpu:
    name: tbm-cpu