version: "3"

services:
  Bot:
    container_name: TBM_CPU
    image: node:19.8.1
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bot.rule=Host(`bot.laura-et-nicolas.com`)"
      - "traefik.http.routers.bot.entrypoints=web"
      - "traefik.http.routers.bot.tls=true"
      - "traefik.http.routers.bot.tls.certresolver=cloudflare"
    environment:
      - TZ= Europe/Paris
    networks:
      - web
    volumes:
      - data:/data
      - git:/git:ro
    command: 
        - bash
        - -c
        - >
          rm -r /data;
          git clone https://github.com/TBMPQF/TBM_CPU_V2.git /data;
          cp /git/config.json /data/config.json;
          cd /data;
          git checkout $COMMIT_REF;
          nodejs index.js;
networks:
    web:
      external: true
volumes:
  data: {}  
  git: {}