version: "3"

services:
  Bot:
    container_name: TBM_CPU
    image: node:lts # 19.8.1 
    restart: no
    labels:
      traefik.enable: true
      traefik.http.routers.cpu.tls: true
      traefik.http.routers.cpu.entrypoints: websecure
      traefik.http.routers.cpu.rule: Host(`cpu.${PERSONAL_DOMAINE_NAME}`)
      traefik.http.services.cpu.loadbalancer.server.port: 80
    environment:
      TZ: Europe/Paris
      UID: ${PERSONAL_UID_CPU}
      GID: ${PERSONAL_GID_CPU}
    networks:
      - web
    volumes:
      - data:/data
      - git:/git:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: 
        - bash
        - -c
        - >
          apt update;
          apt install ffmpeg -y;
          rm -r /data;
          git clone https://github.com/TBMPQF/TBM_CPU_V2.git /data;
          cp /git/config.json /data/config.json;
          cd /data;
          git checkout ${COMMIT_REF};
          nodejs --trace-deprecation index.js;
networks:
    web:
      external: true
volumes:
  data: {}  
  git: {}