version: "3"

services:
  Bot:
    container_name: TBM_CPU
    image: node:lts # 19.8.1 
    restart: unless-stopped
    environment:
      - TZ= Europe/Paris
    networks:
      - web
    volumes:
      - data:/data
      - git:/git:ro
    command: 
        - bash
        - -c
        - >
          rm -r /data;
          git clone https://github.com/TBMPQF/TBM_CPU_V2.git /data;
          cp /git/config.json /data/config.json;
          cd /data;
          git checkout $COMMIT_REF;
          nodejs index.js;
networks:
    web:
      external: true
volumes:
  data: {}  
  git: {}