# Run the line before the first run
# git clone --progress --verbose https://github.com/TBMPQF/TBM_CPU_V2.git /data
version: '3'

services:
  bot:
    restart: unless-stopped
    image: node:lts-alpine
    container_name: tbm-cpu
    hostname: tbm-cpu
    labels:
      diun.enable: true
      diun.watch_repos: true
    environment:
      PUID: 1002
      PGID: 100    
      TZ: Europe/Paris
    volumes:
      - tbm-cpu:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file:
      - stack.env
    command:
      - sh
      - -c
      - > 
        cd /data &&
        apk update && apk add ffmpeg git docker-cli &&
        git pull origin main && git checkout ${COMMIT_REF} &&
        docker logs tbm-cpu --timestamps --since ${LOG_DELAY} > /data/docker_tbm-cpu.log &&
        chmod +x ./CreateConfig.sh && ./CreateConfig.sh &&
        node --trace-deprecation /data/index.js;
    networks:
    - tbm-cpu

volumes:
  tbm-cpu:
    name: tbm_cpu
networks:
  tbm-cpu:
    name: tbm-cpu