version: "3"

services:
  Bot:
    container_name: TEST_TBM_CPU
    image: node:lts
    restart: no
    labels:
      traefik.enable: true
      traefik.http.routers.cpu.tls: true
      traefik.http.routers.cpu.entrypoints: websecure
      traefik.http.routers.cpu.rule: Host(`cpu2.$PERSONAL_DOMAINE_NAME`)
      traefik.http.services.cpu.loadbalancer.server.port: 80
    environment:
      - TZ= Europe/Paris
    volumes:
      - data:/data
      - git:/git:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: 
        - bash
        - -c
        - >
          apt update;
          apt install ffmpeg;
          rm -r /data;
          git clone https://github.com/TBMPQF/TBM_CPU_V2.git /data;
          cp /git/config.json /data/config.json;
          cd /data;
          git checkout $COMMIT_REF;
          nodejs --trace-deprecation index.js;
volumes:
  data: {}  
  git: {}