# Run the line before the first run
# git clone --progress --verbose https://github.com/TBMPQF/TBM_CPU_V2.git /data
version: '3'

services:
  bot:
    restart: unless-stopped
    image: node:lts-alpine
    container_name: tbm-cpu
    hostname: tbm-cpu
    labels:
      diun.enable: true
      diun.watch_repos: true
    environment:
      PUID: 1002
      PGID: 100    
      TZ: Europe/Paris
    volumes:
      - tbm-cpu:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    command:
      - sh
      - -c
      - > 
        cd /data &&
        apk update && apk add ffmpeg git &&        
        touch /data/logs/current_output.log /data/logs/current_error.log &&
        mv /data/logs/current_output.log /data/logs/output.log &&
        mv /data/logs/current_error.log /data/logs/error.log &&
        git reset --hard && git pull origin main && git checkout ${COMMIT_REF} &&
        chmod +x /data/CreateConfig.sh && /data/CreateConfig.sh &&
        node --trace-deprecation /data/index.js > >(tee -a /data/logs/current_output.log) 2> >(tee -a /data/logs/current_error.log >&2) ;
    networks:
    - tbm-cpu

volumes:
  tbm-cpu:
    name: tbm_cpu
networks:
  tbm-cpu:
    name: tbm-cpu